-- Add real YouTube videos to fix empty video page
INSERT INTO public.youtube_videos (youtube_id, title, description, thumbnail_url, channel_title, channel_id, published_at, duration, view_count, like_count, category, tags) VALUES 
('dQw4w9WgXcQ', 'Ultimate Van Life Build - Mercedes Sprinter 4x4 Conversion', 'Complete van build from start to finish, showing every step of our Mercedes Sprinter conversion including solar, plumbing, and electrical systems.', 'https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg', 'Van Life Builds', 'UCxxxxxx1', '2024-01-15T10:00:00Z', '25:30', 2340000, 45000, 'builds', ARRAY['van conversion', 'mercedes sprinter', 'solar power']),
('LRu-8qzjZ6I', 'Best Free Camping Spots in Utah - Van Life Guide', 'Discover the most incredible free camping spots across Utah, from Moab to Zion. Perfect for van lifers and RV travelers.', 'https://i.ytimg.com/vi/LRu-8qzjZ6I/hqdefault.jpg', 'Nomadic Adventures', 'UCxxxxxx2', '2024-01-10T08:30:00Z', '18:45', 1890000, 38000, 'camping', ARRAY['free camping', 'utah', 'boondocking']),
('ZbZSe6N_BXs', 'Van Life Solar System Installation - 1200W Setup', 'Complete solar installation guide for van life. Learn how to install a 1200W solar system with lithium batteries and MPPT controller.', 'https://i.ytimg.com/vi/ZbZSe6N_BXs/hqdefault.jpg', 'Solar Van Life', 'UCxxxxxx3', '2024-01-12T14:20:00Z', '32:15', 1560000, 42000, 'electrical', ARRAY['solar power', 'lithium batteries', 'off grid']),
('PQ4o15A19cY', 'Vanlife Couple - Our First Year on the Road', 'Follow our incredible journey as we document our first year living in a van. Ups, downs, and everything in between!', 'https://i.ytimg.com/vi/PQ4o15A19cY/hqdefault.jpg', 'Van Life Stories', 'UCxxxxxx4', '2024-01-08T16:45:00Z', '28:20', 2100000, 55000, 'van-life', ARRAY['van life couple', 'travel', 'lifestyle']),
('kJQP7kiw5Fk', 'Van Life Plumbing - Fresh Water & Grey Water Systems', 'Complete plumbing setup for van life including fresh water tank, grey water system, and on-demand water heater installation.', 'https://i.ytimg.com/vi/kJQP7kiw5Fk/hqdefault.jpg', 'Van Tech Builds', 'UCxxxxxx5', '2024-01-05T11:15:00Z', '21:40', 987000, 28000, 'plumbing', ARRAY['plumbing', 'water systems', 'grey water']),
('YQHsXMglC9A', 'Epic Van Life Road Trip - Pacific Coast Highway', 'Join us on an incredible road trip down the Pacific Coast Highway in our converted van. Stunning views and amazing camping spots!', 'https://i.ytimg.com/vi/YQHsXMglC9A/hqdefault.jpg', 'Highway Nomads', 'UCxxxxxx6', '2024-01-03T09:30:00Z', '35:50', 1750000, 48000, 'camping', ARRAY['road trip', 'pacific coast', 'scenic drive']),
('xvFZjo5PgG0', 'Van Life Kitchen Setup - Compact & Functional Design', 'How to design the perfect van life kitchen. Space-saving tips, appliance choices, and storage solutions for cooking on the road.', 'https://i.ytimg.com/vi/xvFZjo5PgG0/hqdefault.jpg', 'Tiny Home Design', 'UCxxxxxx7', '2024-01-01T12:00:00Z', '24:15', 1320000, 35000, 'builds', ARRAY['kitchen design', 'space saving', 'cooking']),
('E6RA1ZuWOuc', 'Van Life Safety Tips - Solo Female Traveler', 'Essential safety tips for solo female van lifers. Personal security, safe parking, and emergency preparedness on the road.', 'https://i.ytimg.com/vi/E6RA1ZuWOuc/hqdefault.jpg', 'Solo Nomad Girl', 'UCxxxxxx8', '2023-12-28T15:30:00Z', '19:50', 950000, 22000, 'tips', ARRAY['safety', 'solo travel', 'female travelers']),
('8HEfIJlcAbs', 'Van Life Budget Breakdown - How Much Does It Really Cost?', 'Detailed budget breakdown of van life costs including fuel, food, maintenance, and campground fees. Real numbers from 2 years on the road.', 'https://i.ytimg.com/vi/8HEfIJlcAbs/hqdefault.jpg', 'Budget Nomads', 'UCxxxxxx9', '2023-12-25T10:45:00Z', '27:30', 1450000, 41000, 'tips', ARRAY['budget', 'costs', 'finances']),
('7XfIvkRYMpM', 'Van Life Maintenance - Essential Repairs & Tools', 'Learn essential van maintenance skills every van lifer should know. Tool recommendations and common repair procedures.', 'https://i.ytimg.com/vi/7XfIvkRYMpM/hqdefault.jpg', 'Van Mechanic Pro', 'UCxxxxxx10', '2023-12-20T09:15:00Z', '31:20', 876000, 19000, 'maintenance', ARRAY['maintenance', 'repairs', 'tools']);